version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/service-ip-ranges
  schedule:
    interval: weekly
